language: node_js
dist: xenial
node_js:
  - "10"

cache: npm

script: gatsby build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: gatsbyjs
