language: node_js
dist: xenial
node_js:
  - "10"

cache: npm

script: gatsby build

before_deploy:
  - base64 --decode <<< "$GITHUB_DEPLOY_PRIVATE_KEY" > deploy.key

deploy:
  provider: pages
  edge: true
  deploy_key: ./deploy.key
  local_dir: public
  target_branch: master
  on:
    branch: gatsbyjs
