language: node_js
dist: xenial
node_js:
  - "10"

cache: npm

script: gatsby build

before_deploy:
  - base64 --decode <<< "$GITHUB_DEPLOY_PRIVATE_KEY" > deploy.key

deploy:
  provider: pages:git
  deploy_key: ./deploy.key
  local-dir: public
  target-branch: master
  on:
    branch: gatsbyjs
